name: Integration Tests

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.79.0
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            mantle/target/
          key: ${{ runner.os }}-integration-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run integration tests
        working-directory: mantle
        run: cargo test --locked --test '*' -- --test-threads=1
        env:
          ROBLOSECURITY: ${{ secrets.INTEGRATION_TESTS_COOKIE }}
